### ISSUE TITLE
2018Q3 work log

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-angulardart#89]
_Reorder items using drag-and-drop_.

**Active**ly being worked on:
- [ ] Followup to dart-lang/site-webdev#1819: delete `./scripts`
- [ ] ...

**Next**:
- [ ] Migrate to bootstrap 4 dart-lang/site-webdev#1808
- [ ] Phase out AngularJS directives dart-lang/site-webdev#1747
- [ ] Ensure links to GitHub refer to original page source for Angular Engineering Notes dart-lang/site-webdev#1817
- [ ] Template Syntax: table overflow issue dart-lang/site-webdev#1791
- [ ] Rename `HeroDetailComponent` to `HeroComponent` in Template Syntax, etc dart-lang/site-webdev#1793
- [ ] Router guide: review before Angular 5 final dart-lang/site-webdev#1789
  - [ ] 'Imperative Navigation and Route Parameters' page issue dart-lang/site-webdev#1766
- [ ] Testing guide: review before Angular 5 final dart-lang/site-webdev#1789
- [ ] ACX lottery codelab: fix next/prev link styling dart-lang/site-webdev#1770
- [ ] Example tests: switch back to using headless chrome dart-lang/site-angulardart#86
- [ ] Examples: use event function tearoffs.
- [ ] doc/migrating-to-v5.md should use `webdev` commands https://github.com/dart-lang/angular/issues/1523
- [ ] Gulp analyzer task: use --fatal-infos dart-lang/site-webdev#1715
- [ ] Examples: use analysis_options include?
- [ ] VS Code love dart-lang/site-webdev#1467
- [ ] API docs: link to pub docs dart-lang/site-webdev#1440
- [ ] Make the gallery the primary API reference doc for angular_components dart-lang/site-webdev#1533
- [ ] Angular examples(toh-5, server-comm): `handleError()` looses original exception trace dart-lang/site-webdev#1728
- [ ] Consider using `<base href="/">` in the example apps dart-lang/site-webdev#1725
- [ ] Feedback on page: Imperative Navigation and Route Parameters (DRAFT) dart-lang/site-webdev#1712
- [ ] Example(lifecycle-hooks): E2E failing under Angular +15 dart-lang/site-angulardart#85
- [ ] documentation: template reference variable scope dart-lang/site-webdev#1594
  - Also: a component's static members can be referenced without a receiver in the component's own template.
- [ ] Document "include" in analysis-options https://github.com/dart-lang/site-www/issues/971
- [ ] Ensure links to API pkg entries are versioned dart-lang/site-webdev#1563
- [ ] Make prettify.rb into a gem
- [ ] Structural Directives "next page" link doesn't have a label dart-lang/site-webdev#1713
- [ ] Document main.template.dart dart-lang/site-webdev#1357 
- [ ] Code excerpter issue (toh-5): `<?fixme-code-excerpt "analysis_options.yaml" ...?>`

**Block/awaiting**:
- [ ] Fix selected firebase redirect rules to support URLs optionally ending in .html dart-lang/site-webdev#1778
  - Waiting for list of 301s
- [ ] Roll stagehand pkg:angular version to beta https://github.com/dart-lang/stagehand/issues/547
- [ ] explore deployment of angular_components_example via site-webdev.
- [ ] Add README.md to examples/ng/doc dart-lang/site-webdev#598
- [ ] firebase and superstatic don't redirect `/angular/` to `/angular` dart-lang/site-webdev#1418
  - [ ] In the meantime, trim trailing slash from `page.url` (e.g., in site version dropdown)
  - This sometimes causes problems: e.g., in router page, the following erroneous link can be generated https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/router/router/1#add-router-providers 
- [ ] Document ng-container dart-lang/site-webdev#1540

**Later?**
- [ ] Updated site design followup dart-lang/site-webdev#1580
- [ ] Document new DI features dart-lang/site-webdev#1490
- [ ] **Router guide**: add missing sections - dart-lang/site-webdev#361
- [ ] Cheatsheet code snippets should be excerpt from our main example sources dart-lang/site-webdev#1495
  - Create cheatsheet docregion tags
  - Find & use a markdown syntax for the bootstrap table.
- [ ] Report invalid <?code-pane?> excerpt path+region references https://github.com/chalin/code_excerpt_updater/issues/31
- [ ] Improve copy-code button UX dart-lang/site-webdev#1640

**Submitted**:

- [x] Ensure links to GitHub (page source, and new-issue) work for site-shared pages dart-lang/site-webdev#1489
- [ ] ...

**Done, deployed and confirmed** (selected):

- [x] 'Routing' page issue dart-lang/site-webdev#1799 
- [x] Migrate to jekyll-assets 3.x dart-lang/site-webdev#1329
- [x] Reinstate link checking dart-lang/site-webdev#1792
- [x] Upgrade to Node 10, gulp 4 dart-lang/site-webdev#1775
- [x] Add smoke test to ACX lottery example apps dart-lang/site-webdev#1768
- [x] Drop deprecated materialDirectives dart-lang/site-webdev#1738
- [x] Reinstate example apps depending on next release of pageloader dart-lang/site-webdev#1762
- [x] Update 'Get Started' for Dart 2 dart-lang/site-webdev#1758
- [x] Examples: use unnecessary_const & unnecessary_new
- [x] Tutorial part 5: review before Angular 5 final dart-lang/site-webdev#1422
  - [x] Propagate toh-5 changes to toh-6 (#1755) and router (#1756).
- [x] Upgrade to latest dartdoc dart-lang/site-webdev#1731
- [x] Angular docs: mention use of static variables in templates dart-lang/site-webdev#1630
- [x] update links to old v5 preview site https://github.com/dart-lang/angular/issues/1450
- [x] API Reference displays no data dart-lang/site-webdev#1729
- [x] Example(component-styles): address build warnings (Angular 5-beta+1) dart-lang/site-webdev#1709
- [x] Incorporate or link to dart-lang/angular/doc dart-lang/site-webdev#1689
- [x] Please mention the side effect of Injectable annotation in AngularDart's document dart-lang/site-webdev#1699
- [x] Document @required from the meta library https://github.com/dart-lang/site-www/issues/886
- [x] v5 404s dart-lang/site-webdev#1690
- [x] Split component tests into two tasks
- [x] Articles page doesn't list any articles dart-lang/site-webdev#1686
- [x] Upgrade to SDK 2-dev.67 dart-lang/site-webdev#1684
- [x] Deploy 5-alpha/beta (master) to main server dart-lang/site-webdev#1567
- [x] run dartfmt --fix on examples

**Meta/planning**:
- [ ] 2018Q3 top priority work items dart-lang/site-webdev#1679
