### ISSUE TITLE
2019Q4 work log

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-angulardart#90]
Previous work log: 2018Q3 work log #89.

_Reorder items using drag-and-drop_.

**Active**ly being worked on:
- [ ] ...

**Next**:

- [ ] CI: simplify build process #78
- [ ] Simplify site build #68
- [ ] site.acx_api entries should refer to pub API docs #72

**Block/awaiting**:
- [ ] ...

**Later?**
- [ ] ...

**Submitted**:
- [ ] ...

**Done, deployed and confirmed** (selected, see [here for the complete list][closed PRs]):
- [ ] ...

**Related**:

- Dart 2.6.0-dev analyzer: issues format differs from stable 2.5 release format https://github.com/dart-lang/sdk/issues/38957

[closed PRs]: https://github.com/dart-lang/site-angulardart/milestone/1
