### ISSUE TITLE
2018Q3 top priority work items

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-angulardart#92]
Some items have been carried over from the previous quarter (#1456).

### Major

- [x] Deploy 5-alpha/beta (master) to main server dart-lang/site-webdev#1567
- [ ] Pages to review before Angular 5 final dart-lang/site-webdev#1422

### Documentation

- [ ] Finish router guide dart-lang/site-webdev#361
- [ ] API docs: link to pub docs dart-lang/site-webdev#1440
- [ ] [new 4.0 features](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#400):
  - [ ] functional structural directives dart-lang/site-webdev#1191
  - [ ] `@deferred` "compile-time" directive
- [ ] forms
  - [ ] adjust sample and prose to promote use of class bindings dart-lang/site-webdev#366 
- [ ] E2E dart-lang/site-webdev#895 

Others:
- [ ] how to make a Dart web app offline-capable dart-lang/site-webdev#593
- [ ] Reuse Matan's Medium.com lazy-loading article dart-lang/site-webdev#582 
- [ ] i18n dart-lang/site-webdev#866
- [ ] security page updates: HTTP-level vulnerabilities & HTML sanitization dart-lang/site-webdev#351
- [ ] how to debug your web app dart-lang/site-webdev#819
- [ ] ng-content and ngProjectAs aren't documented dart-lang/site-webdev#617
- [ ] best practices dart-lang/site-webdev#438
- [ ] communication between components via service dart-lang/site-webdev#437
- [ ] ~use of Dart logger as part of ng examples dart-lang/site-webdev#425~
- [ ] how to style angular components dart-lang/site-webdev#348

### Infrastructure

- [ ] Continue to decrease technical debt of site-www and site-webdev - dart-lang/site-webdev#637 
- [ ] gulp tasks: switch to using pump dart-lang/site-webdev#1042
- [ ] Sidenav improvements - dart-lang/site-webdev#1018
- [ ] TOC improvements - dart-lang/site-webdev#868
- [ ] check external links dart-lang/site-webdev#784
- [ ] Consolidate Angular subsite and webdev styles - dart-lang/site-webdev#980
  - Migrate to Bootstrap 4 - https://github.com/dart-lang/site-webdev/issues/980#issuecomment-359452381

### Doc & examples

- [ ] Update [angular][] API docs
  - [ ] Update [angular2.core/Query](https://webdev.dartlang.org/angular/api/angular2.core/Query); also see https://github.com/dart-lang/angular2/issues/249.
  - [ ] https://github.com/dart-lang/angular2/issues/247
- [ ] Update tutorial and its examples to use ACX - dart-lang/site-webdev#399 (most likely after 5.x)
- [ ] Feature AngularDart Components in the Angular docs dart-lang/site-webdev#176

[angular]: https://github.com/dart-lang/angular2
[angular_test]: https://github.com/dart-lang/angular_test
[angular_components]: https://github.com/dart-lang/angular2_components
